### ISSUE TITLE
V1 Release Checklist

### ISSUE THREAD

**Issue by petyosi** [petyosi/react-virtuoso#207]
The list below is the TODO for the `v1` release. Develop happens in the `next` branch.
- [x] A new website (docusaurus)
  - [x] API Reference
    - [x] Virtuoso
    - [x] Grouped Virtuoso
    - [x] Virtuoso Grid
  - [x] Customize look and feel
    - [ ] Navigation header / footer
  - [x] Data Generator, prettier example items
  - [x] Google Analytics
- [ ] Review open issues, link to v1 if resolution
- [x] Update README
- [x] Instructions for collaboration, including how to run the test cases.

- [ ] Set up semantic release with github workflow for package / site
- [x] Clean-up branches / tag `v0`

### Post V1 release

- [ ] Bottom align for short list
- [ ] Extrapolate `scrollTop` location for extremely large lists
- [ ] `resetEndReached` method
